site_name: Software Engineering Knowledge Base
site_url: https://jgrieger.github.io/sw-engineering-kb
copyright: Copyright &copy; 2025 Jacob Grieger
repo_url: https://github.com/jgrieger/sw-engineering-kb/
edit_uri: edit/main/docs/
strict: true
